pipeline {
    agent { 
        label 'vm4' 
        }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t quay.tiplab.local/openetra/be:dev -f $HOME/NETRA/netra_backend/deployment/Dockerfile.base $HOME/NETRA/netra_backend/'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push quay.tiplab.local/openetra/be:dev'
                }
            }
        }
        stage('Restart Docker Compose') {
            steps {
                script {
                    sh 'docker compose -f $HOME/NETRA/netra_backend/deployment/docker-compose.yml down backend'
                    sh 'docker compose -f $HOME/NETRA/netra_backend/deployment/docker-compose.yml up backend -d'
                }
            }
        }
        stage('Clean Jenkins Workspace') {
            steps {
                cleanWs()
            }
        }
    }
}