pipeline {
    agent { 
        label 'vm4'
    }
    environment{
        GITHUB_ACCESS_TOKEN = credentials("github_access_token")
    }
    stages {
        stage('Setup Environment'){
            steps{
                script{
                    dir('AN-ORCA-FE'){
                        git branch: 'bagus',
                           //credentialsId: 'github_access_token',
                            url: "https://github.com/whiwk/caps_frontend.git"
                        script{
                            env.COMMIT_SHORT_SHA = sh (
                                script: 'git log --pretty=format:\'%h\' -n 1',
                                returnStdout: true
                            ).trim()
                        }
                    }
                    def title = "Pipeline orca/frontend ${env.JOB_BASE_NAME} #${env.BUILD_NUMBER}"
                    discordSend description: 'Pipeline has started.', 
                                link: env.BUILD_URL, 
                                result: 'STARTED', 
                                title: title, 
                                webhookURL: env.DISCORD_WEBHOOK
                }
            }           
        }
        stage('Build Image') {
            steps {
                script {
                    dir('AN-ORCA-FE') {
                        sh 'docker build -t quay.tiplab.local/orca/fe:${COMMIT_SHORT_SHA} .'
                    }
                }
            }
            post{
                success {
                    script{
                        echo "Success, continue to next stage..."
                    }
                }
                failure {
                    script{
                        error "Failed, exiting now..."
                    }
                }
                aborted {
                    script{
                        error "Aborted, exiting now..."
                    }
                }
                unstable {
                    script{
                        error "Unstable, exiting now..."                    
                    }
                }
            }
        }
        stage('Push Image and delete locally') {
            steps {
                script {
                    sh 'docker push quay.tiplab.local/orca/fe:${COMMIT_SHORT_SHA}'
                    sh 'docker rmi quay.tiplab.local/orca/fe:${COMMIT_SHORT_SHA}'
                }
            }
        }
        stage('Change Image Tag on Github'){
                    steps {
                        script{
                            env.GIT_URL = "https://oauth2:${GITHUB_ACCESS_TOKEN}@github.com/adaptivenetworklab/AN-OPEN-NETRA-MANIFESTS.git"
                        }
                        dir('AN-ORCA-MANIFESTS'){
                            git branch: 'main',
                                url: "$GIT_URL"
                            sh 'git config user.email gintingari73@gmail.com && git config user.name arigints'
                            sh 'sed -i "s+quay.tiplab.local/orca/fe:.*+quay.tiplab.local/orca/fe:${COMMIT_SHORT_SHA}+g" app/overlay/staging/frontend/deployment.yaml'
                            sh 'git add . && git commit -m "(bot) update frontend deployment.yaml image tag to ${COMMIT_SHORT_SHA}" || true'
                            sh 'git push origin main'
                        }
                    }
                }
        stage('Argocd Setup') {
            steps {
                withCredentials([string(credentialsId: "argocd-auth-token", variable: 'ARGOCD_AUTH_TOKEN')]) {
                    sh "argocd repo add https://github.com/adaptivenetworklab/AN-OPEN-NETRA-MANIFESTS.git --type git --username arigints --password ${GITHUB_ACCESS_TOKEN} --upsert"
                    sh 'ARGOCD_SERVER=10.30.1.214:31844 argocd --grpc-web app create orca-fe-staging --project default --repo https://github.com/adaptivenetworklab/AN-OPEN-NETRA-MANIFESTS.git --path app/overlay/staging/frontend --revision main --dest-namespace staging --dest-server https://kubernetes.default.svc --upsert'
                }
            }
        }
        stage('Argocd Sync') {
            steps {
                withCredentials([string(credentialsId: "argocd-auth-token", variable: 'ARGOCD_AUTH_TOKEN')]) {
                    sh 'argocd --grpc-web app sync orca-fe-staging --prune --force'
                }
            }
        }
    }
    post {
        success {
            script {
                // Send notification to Discord on successful completion
                def result = currentBuild.currentResult.toLowerCase()
                discordSend webhookURL: DISCORD_WEBHOOK,
                            result: currentBuild.currentResult,
                            description: "**Build:** ${env.BUILD_NUMBER}\n**Status:** ${result}\n\u2060", /* word joiner character forces a blank line */
                            notes: "Hey <@588945460719255562>, here's some Notes!",
                            showChangeset: true
            }
        }
        failure {
            script {
                // Send notification to Discord on failure
                discordSend webhookURL: env.DISCORD_WEBHOOK,
                            description: 'Pipeline has failed.',
                            result: 'FAILURE', 
                            notes: "Hey <@588945460719255562>, the pipeline is failure"
            }
        }
        aborted {
            script {
                // Send notification to Discord on failure
                discordSend webhookURL: env.DISCORD_WEBHOOK,
                            description: 'Pipeline has aborted.',
                            result: 'ABORTED', 
                            notes: "Hey <@588945460719255562>, the pipeline is aborted"           
            }
        }
        unstable {
            script {
                // Send notification to Discord on failure
                discordSend webhookURL: env.DISCORD_WEBHOOK,
                            description: 'Pipeline has unstable.',
                            result: 'UNSTABLE', 
                            notes: "Hey <@588945460719255562>, the pipeline is unstable"
            }
        }
        always {
            deleteDir()
            dir("${workspace}@tmp") {
                deleteDir()
            }
            dir("${workspace}@script") {
                deleteDir()
            }
        }
    }
}