apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeview
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: "kubeview.orca.edu"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: kubeview
                port:
                  number: 80