apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  ingressClassName: nginx
  rules:
    - host: "longhorn.orca.edu"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80