apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: auth-secret
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
spec:
  ingressClassName: nginx
  rules:
    - host: "longhorn.openetra.net"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80