jenkins:
  systemMessage: |
    "100% Immutable, All configuration for this jenkins is done as code (JCasC)"
  numExecutors: 1
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "ari"
          name: "Ari Erginta Ginting"
          password: "ari123"
        - id: "bagus"
          name: "Bagus Dwi Prasetyo"
          password: "bagus"
        - id: "ima"
          name: "Ima Dewi Arofani"
          password: "ima"
        - id: "rafli"
          name: "Mochamad Rafli Hadiana"
          password: "rafli"
        - id: "user"
          name: "Authenticated"
          password: "user"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "ari"
              - user: "rafli"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            entries:
              - user: "user"
              - user: "bagus"
              - user: "ima"
        items:
          - name: "Folder orca"
            description: "Jobs in Folder ORCA, but not the folder itself"
            pattern: "orca/.*"
            permissions:
              - "Job/Read"
              - "Job/Build"
              - "Job/Cancel"
              - "View/Read"
            entries:
              - user: "bagus"
              - user: "ima"
  nodes:
    - permanent:
        labelString: "agent for development"
        mode: "EXCLUSIVE"
        name: "vm4"
        numExecutors: 1
        remoteFS: "/var/lib/jenkins"
        launcher:
          ssh:
            host: "10.30.1.221"
            port: 22
            credentialsId: "agent-creds"
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              nonVerifyingKeyVerificationStrategy: {}
  globalNodeProperties:
  - envVars:
      env:
      - key: "DISCORD_WEBHOOK"
        value: "https://discord.com/api/webhooks/1254708328790233200/B4-aQudHShqqThHA1Bq59DVBzAs_HT5KZ6toNYn9CBGEfOBQAxFNyQaYaeyCpECJD-J0"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "agent-creds"
              username: "bagus"
              password: "bagus"
              description: "Credentials for connecting development VM as jenkins agent"
          - string:
              scope: GLOBAL
              id: "argocd-auth-token"
              secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3MTA1MTQyMTAsImlhdCI6MTcxMDUxNDIxMCwianRpIjoiYTFkNGNjN2QtMzE2Mi00MzU3LWE5NzctNmI2NzMxZTc5NjY3In0.kME5h_q37Vqtv3aHrzjzAGXDw9MgJKUYch5RsAVahrg"
              description: "Credentials for Argo CD token"
          - string:
              scope: GLOBAL
              id: "github_access_token"
              secret: "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"
              description: "Token for Github Repositories"
jobs:
  - script: >
      pipelineJob("initial-dsl") {
        definition {
          cps {
            script('''
              pipeline {
                agent {
                  label 'vm4'
                }
                stages {
                  stage('seed or update all pipelines') {
                    steps {
                      dir('initial-dsl-folder') {
                        git branch: 'main',
                            url: 'https://github.com/adaptivenetworklab/AN-OPEN-NETRA-INFRA'
                        jobDsl targets: [
                            'pipeline/create_folder.groovy',
                            'pipeline/*/*.groovy'
                        ].join('\\n')
                      }
                    }
                  }
                }
                post {
                  always {
                    deleteDir()
                    dir("${workspace}@tmp") {
                      deleteDir()
                    }
                    dir("${workspace}@script") {
                      deleteDir()
                    }
                  }
                }
              }
            '''.stripIndent())
            sandbox()
          }
        }
      }
unclassified:
  location:
    url: http://jenkins.orca.edu
    adminAddress: "gintingari73@gmail.com"