jenkins:
  systemMessage: |
    Welcome to our build server.

    This Jenkins is 100% configured and managed 'as code'.
    Config is now mostly handled by the 'Jenkins Configuration as Code' (JCasC) plugin.
    JCasC config can be found in the jenkins.yaml file in the $JENKINS_HOME/casc/ folder.

    Some settings are still injected from init.groovy.d scripts,
    but these settings will be ported over to JCasC as support becomes available.
  numExecutors: 1
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
        - id: user
          name: "User"
          password: 123
          properties:
            - mailer:
                emailAddress: "user@example.com"
  authorizationStrategy:
    globalMatrix:
      entries:
        - "admin:Overall/Administer"
        - "authenticated:Overall/Read"
        - "user:Job/Build"
        - "user:Job/Cancel"
        - "user:Job/Read"
        - "user:Job/Discover"
        - "authenticated:Job/Read"
        - "anonymous:View/Read"
  nodes:
    - permanent:
        labelString: "agent for development"
        mode: NORMAL
        name: "vm4"
        numExecutors: 1
        remoteFS: "/var/lib/jenkins"
        launcher:
          SSHLauncher:
            host: "10.30.1.221"
            port: 22
            credentialsId: agent-creds
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              nonVerifyingKeyVerificationStrategy: {}
jobs:
  - script: >
      pipelineJob("inital-dsl") {
        definition {
          cps{
            script('''
              pipeline {
                agent {
                  label 'vm4'
                }
                stages {               
                  stage('seed or update all pipelines') {
                    steps{
                      dir('initial-dsl-folder'){
                        git branch: 'main',
                            url: 'https://github.com/adaptivenetworklab/AN-OPEN-NETRA-INFRA'
                        jobDsl targets: [
                            'pipeline/create_folder.groovy',
                            'pipeline/*/*.groovy'
                        ].join('\\n')
                      }
                    }
                  }               
                }
                post { 
                  always { 
                    deleteDir()
                    dir("${workspace}@tmp") {
                      deleteDir()
                    }
                    dir("${workspace}@script") {
                      deleteDir()
                    }
                  }
                }
              } 
            '''.stripIndent())
            sandbox()        
          }
        }
      }             
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "agent-creds"
              username: "bagus"
              password: "bagus"
              description: "Username/Password Credentials for connecting development VM as jenkins agent"